runtime: python39

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  SECRET_KEY: "your-strong-secret-key"   # Replace with your secure secret key
  REDIS_URL: "redis://redis-master.default.svc.cluster.local:6379"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    secure: always
    script: auto
