apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dashboard-service
  template:
    metadata:
      labels:
        app: dashboard-service
    spec:
      containers:
        - name: dashboard-container
          image: your-docker-hub-id/your-image-name:latest
          ports:
            - containerPort: 8000