replicaCount: 3

image:
  repository: gcr.io/hopkinstimesheetproj/dashboard-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

redis:
  createSecret: false
  host: 10.155.183.243
  port: "6379"
  password: 70a21bc8-d827-4cfd-8ec1-d2b5cce8af81

userManagementService:
  url: http://user-management-service.default.svc.cluster.local
